### ISSUE TITLE
Issue with Coster

### ISSUE THREAD

**Issue by KevM92** [gabrielweyer/azure-vm-pricing#283]
Hi @gabrielweyer,

I just tried it with the newest patch, and it's all good, besides an essential issue. 
I created this CSV for Coster to take and add prices: 
![image](https://github.com/user-attachments/assets/2d96d007-59a0-49c5-b529-2b67a99567b2)
Unfortunately, Coster doesn't provide any prices besides the fact that it has all pricing json files: 
![image](https://github.com/user-attachments/assets/3a2e4aa3-404f-460c-934c-259f4bcbccf0)
![image](https://github.com/user-attachments/assets/8a92dc4f-5df8-43db-98f3-3159edc2bebf)
So, based on the guide on the GitHub Page, this should be sufficient by my understanding because if we look in csv's and try it on the first VM config, there are more than enough options to take pricing from 
![image](https://github.com/user-attachments/assets/c06d5284-6a0b-4331-984f-61d53b90ac37)
![image](https://github.com/user-attachments/assets/376ee6b8-4b52-45fd-b9eb-631424cb8195)
By the way - as I don't know what the expected result would be here, I hope it would ignore the B Series VMs as the Burstable VMs are only useful in certain scenarios and should be used as a price optimization option VM by VM and not in a cost indication that you would do with a lift and shift approach. 
Thanks,
Kev

**Comment by gabrielweyer** [comment]
Thanks for your detailed bug report. There were a couple of issues:

- When I updated the Coster to use System.Text.Json instead of Json.NET, I broke parsing prices. This is now fixed. I added a test that will prevent further regressions.
- You used 'Windows' (upper-case 'W') instead of 'windows' in the 'Operating System' column. I made the Coster case-insensitive when parsing the Operating System and the Region, so this shouldn't be an issue anymore.

Currently the tool doesn't exclude any VM series. I'll look into making it possible to ignore some series. In the meantime you could remove these series from the pricing files.

**Comment by gabrielweyer** [comment]
@KevM92 I've added the ability to discard specific VMs:

```powershell
dotnet run --configuration Release -- --input <input-path> --configuration <configuration-path>
```

Where `<configuration-path>` points to a file containing:

```json
{
  "excludedVms": [
    "B2ts v2",
    "B2ls v2",
    "B2s v2",
    "B4ls v2",
    "B4s v2",
    "B8ls v2",
    "B8s v2",
    "B16ls v2",
    "B16s v2",
    "B32ls v2",
    "B32s v2",
    "B2ats v2",
    "B2als v2",
    "B2as v2",
    "B4als v2",
    "B4as v2",
    "B8als v2",
    "B8as v2",
    "B16als v2",
    "B16as v2",
    "B32als v2",
    "B32as v2",
    "B1s",
    "B1ms",
    "B2s",
    "B2ms",
    "B4ms",
    "B8ms",
    "B12ms",
    "B16ms",
    "B20ms"
  ]
}
```

This will ignore all burstable VMs when costing.

**Comment by gabrielweyer** [comment]
Closing this as it has been inactive for a while. Feel free to re-open.
